web/image_classifier/urls.py
from django.urls import path
from . import views

app_name = "image_classifier"

urlpatterns = [
        path('upload_image', views.uploaded_image, name='upload_image')
]

web/recipes/urls.py
from django.urls import path, include
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('recipe/result/<str:label>/', views.recipe_view, name='result'),
    path('recipe/<str:meal_id>/', views.recipe_detail_view, name="recipe_detail"),

]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('image_classifier/', include('image_classifier.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/image_classifier/models.py
from django.db import models


class UploadedImage(models.Model):
    # Automatically saved in media/images/
    image = models.ImageField(upload_to="uploaded_images/")
    

web/recipes/models.py
from django.db import models

# Create your models here.

web/image_classifier/forms.py
from django import forms
from .models import UploadedImage


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = UploadedImage
        fields = ["image"]

web/image_classifier/views.py
from django.shortcuts import render, redirect
from .forms import ImageUploadForm
from .classification_model import image_classify
import logging
logger = logging.getLogger(__name__)


def uploaded_image(request):
    """
    This is the view for uploading image.
    """
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            image_instance = form.save()
            image_path = image_instance.image.path
            predicted_label = image_classify(image_path)
            return redirect('recipes:result', label=predicted_label)
    else:
        form = ImageUploadForm()

    return render(request, 'image_classifier/upload.html', {'form': form})

web/recipes/views.py
from django.shortcuts import render
from . import get_recipes



def home(request):
    return render(request, "recipes/home.html")


def recipe_view(request, label):
    """
    This is the view for displaying the recipe results.
    """
    all_recipes_by_ingredient = get_recipes.get_recipes_by_ingredient(label)
    display_recipes = get_recipes.get_fixed_num_recipes(3, all_recipes_by_ingredient)

    context = {
        'recipes':display_recipes
    }
    return render(request, "recipes/recipes_result.html", context)


def about(request):
    """
    This is the view for about page.
    """
    return render(request, "recipes/about.html")

def recipe_detail_view(request, meal_id):
    """"
    This is the view for displaying recipe details.
    """
    recipe = get_recipes.get_recipe_detail(meal_id)

    context = {
        'recipe':recipe
    }

    print(context)
    return render(request, "recipes/recipe_detail.html", context)

web/image_classifier/templates/image_classifier/upload.html
{% extends 'recipes/base.html' %}
{% load widget_tweaks %}

{% block title %}Upload File{% endblock title %}

{% block content %}
    <h2>Please upload your image!</h2>
    <!-- Upload File -->
<br>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3" style="margin-left: 80px;>
                {{ form.image.label_tag }}  <!-- Render the label -->
                {{ form.image }}  <!-- Render the file input -->
            </div>
            <button type="submit" class="btn btn-primary" style="margin-right: 50px;">Upload</button>
        </form>
        
    
    
      
{% endblock content %}

web/image_classifier/templates/image_classifier/upload_success.html
<p>Image uploaded successfully!</p>

web/recipes/templates/recipes/about.html
{% extends 'recipes/base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
    <section id="about" class="my-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-center">About Our Tool</h2>
                    <p class="text-center mt-3">
                        Hi! This is Joy! Welcome to Green Gourmet Guide!
                    </p>
                    <p class="text-center mt-3">
                        Our tool identifies vegetables from your images and suggests delicious recipes to ignite your cooking passion.
                    </p>

                    <p class="text-center mt-2">
                        Inspired by everyday grocery challenges, it's designed to simplify meal planning and enhance the cooking experience for novices and seasoned food enthusiasts alike. 
                    </p>
                    <p class="text-center mt-2">
                        Special thanks to the <a href="https://www.themealdb.com/api.php" target="_blank">theMealDB API</a> and the <a href="https://huggingface.co/jazzmacedo/fruits-and-vegetables-detector-36" target="_blank">fruits-and-vegetables-detector-36</a> model for making this possible. 
                        Explore our source code on <a href="https://github.com/joyxxi/green_gourmet_guide" target="_blank">GitHub</a>
                    </p>

                </div>
            </div>
        </div>
    </section>
    
{% endblock content %}

web/recipes/templates/recipes/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Site{% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <style>
      .content-spacing {
        margin-bottom: 100px;
      }
        body {
            font-family: 'Comic Sans MS', 'Chalkboard SE', 'Marker Felt', sans-serif;
            color: #006400;
            text-align: center; 
        }

        h1 {
            color: #159947; 
            font-size: 3em; 
            text-shadow: 2px 2px 0px #E2CFC9;
        }

        h2 {
            color: #3C8046; 
            font-size: 2em;
            text-shadow: 1px 1px 0px #BFD8C4; 
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'recipes:home' %}">
            <img src="{% static "recipes/images/logo.png" %}" alt="Bootstrap" width="120" height="70">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'recipes:home' %}" style="font-family: 'Comic Sans MS', sans-serif; font-size: 1.2rem; color: #006400;">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'recipes:about' %}" style="font-family: 'Comic Sans MS', sans-serif; font-size: 1.2rem; color: #006400;">About</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    <main class="content-spacing">
        {% block content %}
        {% endblock content %}
    </main>


    
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
    integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
    crossorigin="anonymous"
  ></script>
    <!-- Add other global scripts here -->
</body>
</html>

web/recipes/templates/recipes/home.html
{% extends 'recipes/base.html' %}
{% load widget_tweaks %}

{% block title %}Home{% endblock title %}

{% block content %}
<br><br><br>
<h1>Welcome to Green Gourmet Guide!</h1>
<br><br>
<h2>📸 Snap a Pic & Let's Search by Image!</h2>

<br><br>

<div class="d-grid gap-2 col-2 mx-auto">
    <a class="btn btn-outline-warning" href="{% url 'image_classifier:upload_image' %}" role="button"
    style="width: 200px; height: 60px; --bs-btn-font-size: 1.75rem; display: inline-block;"
    >Upload</a>
  </div>

<br><br> 


{% endblock content %}

web/recipes/templates/recipes/recipe_detail.html
{% extends 'recipes/base.html' %}

{% block title %}result{% endblock title %}

{% block content %}
    {% if recipe %}
    <h2 class="text-center">{{ recipe.0.strMeal }}</h2>
    <img src="{{ recipe.0.strMealThumb }}" class="rounded mx-auto d-block" alt="{{ recipe.0.strMeal }}" style="width: 500px; height: 500px; object-fit: cover;">
    <p style="padding: 0 40px;">Instructions: {{ recipe.0.strInstructions }}</p>
{% else %}
    <p>Recipe details not available.</p>
{% endif %}
{% endblock content %}

web/recipes/templates/recipes/recipes_result.html
{% extends 'recipes/base.html' %}

{% block title %}Results{% endblock title %}

{% block content %}
    <br><br>
    {% if recipes == null %}
    <h2>Oopsie-daisy! We haven't cooked up any recipes like that yet!</h2>
    {% endif %}
    <div class="row row-cols-1 row-cols-md-3 g-4 pl-4">
        {% for recipe in recipes %}
            <div class="col">
                <div class="card text-center mb-3 mx-auto" style="width: 20rem;">
                    <img src="{{ recipe.strMealThumb }}" class="card-img-top" alt="{{ recipe.strMeal }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.strMeal }}</h5>
                        <a href="{% url 'recipes:recipe_detail' meal_id=recipe.idMeal %}" class="btn btn-primary">Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        
    </div>
    

{% endblock content %}